<?xml version="1.0" encoding="UTF-8"?><testrun name="AppTest (1)" project="Test" tests="3" started="3" failures="1" errors="0" ignored="0">
  <testsuite name="testall.Test.AppTest" time="0.0">
    <testcase name="testApp" classname="testall.Test.AppTest" time="0.0"/>
    <testcase name="testBalance1" classname="testall.Test.AppTest" time="0.0">
      <failure>junit.framework.AssertionFailedError: expected:&lt;true&gt; but was:&lt;false&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:47)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:282)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:64)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:149)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:155)&#13;
	at testall.Test.AppTest.testBalance1(AppTest.java:44)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:498)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:154)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:127)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:106)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&#13;
	at junit.framework.TestResult.run(TestResult.java:109)&#13;
	at junit.framework.TestCase.run(TestCase.java:118)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:208)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:203)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:121)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testBalance" classname="testall.Test.AppTest" time="0.0"/>
  </testsuite>
</testrun>
